//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.15 at 02:29:41 PM CEST 
//


package com.example.applicationsoap.soapmodel.lanemodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LaneSoap" type="{http://example.com/applicationsoap/soapmodel/lanemodel}LaneSoap"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "laneSoap"
})
@XmlRootElement(name = "DeleteLaneResponse")
public class DeleteLaneResponse {

    @XmlElement(name = "LaneSoap", required = true)
    protected LaneSoap laneSoap;

    /**
     * Gets the value of the laneSoap property.
     * 
     * @return
     *     possible object is
     *     {@link LaneSoap }
     *     
     */
    public LaneSoap getLaneSoap() {
        return laneSoap;
    }

    /**
     * Sets the value of the laneSoap property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaneSoap }
     *     
     */
    public void setLaneSoap(LaneSoap value) {
        this.laneSoap = value;
    }

}
