//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.26 at 01:21:09 AM CEST 
//


package com.example.applicationsoap.soapmodel.lanemodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LANE_TYPE_Soap.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LANE_TYPE_Soap"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="normal"/&gt;
 *     &lt;enumeration value="premium"/&gt;
 *     &lt;enumeration value="vip"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LANE_TYPE_Soap")
@XmlEnum
public enum LANETYPESoap {

    @XmlEnumValue("normal")
    NORMAL("normal"),
    @XmlEnumValue("premium")
    PREMIUM("premium"),
    @XmlEnumValue("vip")
    VIP("vip");
    private final String value;

    LANETYPESoap(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LANETYPESoap fromValue(String v) {
        for (LANETYPESoap c: LANETYPESoap.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
