//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.26 at 01:21:09 AM CEST 
//


package com.example.applicationsoap.soapmodel.lanemodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.applicationsoap.soapmodel.lanemodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.applicationsoap.soapmodel.lanemodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReadAllLaneRequest }
     * 
     */
    public ReadAllLaneRequest createReadAllLaneRequest() {
        return new ReadAllLaneRequest();
    }

    /**
     * Create an instance of {@link ReadAllLaneResponse }
     * 
     */
    public ReadAllLaneResponse createReadAllLaneResponse() {
        return new ReadAllLaneResponse();
    }

    /**
     * Create an instance of {@link LaneSoap }
     * 
     */
    public LaneSoap createLaneSoap() {
        return new LaneSoap();
    }

    /**
     * Create an instance of {@link ReadOneLaneRequest }
     * 
     */
    public ReadOneLaneRequest createReadOneLaneRequest() {
        return new ReadOneLaneRequest();
    }

    /**
     * Create an instance of {@link ReadOneLaneResponse }
     * 
     */
    public ReadOneLaneResponse createReadOneLaneResponse() {
        return new ReadOneLaneResponse();
    }

    /**
     * Create an instance of {@link CreateLaneRequest }
     * 
     */
    public CreateLaneRequest createCreateLaneRequest() {
        return new CreateLaneRequest();
    }

    /**
     * Create an instance of {@link CreateLaneResponse }
     * 
     */
    public CreateLaneResponse createCreateLaneResponse() {
        return new CreateLaneResponse();
    }

    /**
     * Create an instance of {@link UpdateLaneRequest }
     * 
     */
    public UpdateLaneRequest createUpdateLaneRequest() {
        return new UpdateLaneRequest();
    }

    /**
     * Create an instance of {@link UpdateLaneResponse }
     * 
     */
    public UpdateLaneResponse createUpdateLaneResponse() {
        return new UpdateLaneResponse();
    }

    /**
     * Create an instance of {@link DeleteLaneRequest }
     * 
     */
    public DeleteLaneRequest createDeleteLaneRequest() {
        return new DeleteLaneRequest();
    }

    /**
     * Create an instance of {@link DeleteLaneResponse }
     * 
     */
    public DeleteLaneResponse createDeleteLaneResponse() {
        return new DeleteLaneResponse();
    }

}
