//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.07 at 04:54:12 PM CEST 
//


package com.example.applicationsoap.soapmodel.usermodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.applicationsoap.soapmodel.usermodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.applicationsoap.soapmodel.usermodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReadAllUserRequest }
     * 
     */
    public ReadAllUserRequest createReadAllUserRequest() {
        return new ReadAllUserRequest();
    }

    /**
     * Create an instance of {@link ReadAllUserResponse }
     * 
     */
    public ReadAllUserResponse createReadAllUserResponse() {
        return new ReadAllUserResponse();
    }

    /**
     * Create an instance of {@link UserSoap }
     * 
     */
    public UserSoap createUserSoap() {
        return new UserSoap();
    }

    /**
     * Create an instance of {@link ReadOneUserRequest }
     * 
     */
    public ReadOneUserRequest createReadOneUserRequest() {
        return new ReadOneUserRequest();
    }

    /**
     * Create an instance of {@link ReadOneUserResponse }
     * 
     */
    public ReadOneUserResponse createReadOneUserResponse() {
        return new ReadOneUserResponse();
    }

    /**
     * Create an instance of {@link CreateUserRequest }
     * 
     */
    public CreateUserRequest createCreateUserRequest() {
        return new CreateUserRequest();
    }

    /**
     * Create an instance of {@link CreateUserResponse }
     * 
     */
    public CreateUserResponse createCreateUserResponse() {
        return new CreateUserResponse();
    }

    /**
     * Create an instance of {@link UpdateUserRequest }
     * 
     */
    public UpdateUserRequest createUpdateUserRequest() {
        return new UpdateUserRequest();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link ReadManyUserRequest }
     * 
     */
    public ReadManyUserRequest createReadManyUserRequest() {
        return new ReadManyUserRequest();
    }

    /**
     * Create an instance of {@link ReadManyUserResponse }
     * 
     */
    public ReadManyUserResponse createReadManyUserResponse() {
        return new ReadManyUserResponse();
    }

    /**
     * Create an instance of {@link DeactivateUserRequest }
     * 
     */
    public DeactivateUserRequest createDeactivateUserRequest() {
        return new DeactivateUserRequest();
    }

    /**
     * Create an instance of {@link DeactivateUserResponse }
     * 
     */
    public DeactivateUserResponse createDeactivateUserResponse() {
        return new DeactivateUserResponse();
    }

    /**
     * Create an instance of {@link ActivateUserRequest }
     * 
     */
    public ActivateUserRequest createActivateUserRequest() {
        return new ActivateUserRequest();
    }

    /**
     * Create an instance of {@link ActivateUserResponse }
     * 
     */
    public ActivateUserResponse createActivateUserResponse() {
        return new ActivateUserResponse();
    }

}
