//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.26 at 01:21:09 AM CEST 
//


package com.example.applicationsoap.soapmodel.reservationmodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.applicationsoap.soapmodel.reservationmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.applicationsoap.soapmodel.reservationmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReadAllReservationRequest }
     * 
     */
    public ReadAllReservationRequest createReadAllReservationRequest() {
        return new ReadAllReservationRequest();
    }

    /**
     * Create an instance of {@link ReadAllReservationResponse }
     * 
     */
    public ReadAllReservationResponse createReadAllReservationResponse() {
        return new ReadAllReservationResponse();
    }

    /**
     * Create an instance of {@link ReservationSoap }
     * 
     */
    public ReservationSoap createReservationSoap() {
        return new ReservationSoap();
    }

    /**
     * Create an instance of {@link ReadOneReservationRequest }
     * 
     */
    public ReadOneReservationRequest createReadOneReservationRequest() {
        return new ReadOneReservationRequest();
    }

    /**
     * Create an instance of {@link ReadOneReservationResponse }
     * 
     */
    public ReadOneReservationResponse createReadOneReservationResponse() {
        return new ReadOneReservationResponse();
    }

    /**
     * Create an instance of {@link CreateReservationRequest }
     * 
     */
    public CreateReservationRequest createCreateReservationRequest() {
        return new CreateReservationRequest();
    }

    /**
     * Create an instance of {@link CreateReservationResponse }
     * 
     */
    public CreateReservationResponse createCreateReservationResponse() {
        return new CreateReservationResponse();
    }

    /**
     * Create an instance of {@link EndReservationRequest }
     * 
     */
    public EndReservationRequest createEndReservationRequest() {
        return new EndReservationRequest();
    }

    /**
     * Create an instance of {@link EndReservationResponse }
     * 
     */
    public EndReservationResponse createEndReservationResponse() {
        return new EndReservationResponse();
    }

    /**
     * Create an instance of {@link DeleteReservationRequest }
     * 
     */
    public DeleteReservationRequest createDeleteReservationRequest() {
        return new DeleteReservationRequest();
    }

    /**
     * Create an instance of {@link DeleteReservationResponse }
     * 
     */
    public DeleteReservationResponse createDeleteReservationResponse() {
        return new DeleteReservationResponse();
    }

}
