//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.15 at 02:29:41 PM CEST 
//


package com.example.applicationsoap.soapmodel.reservationmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReservationSoap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReservationSoap"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="laneUuid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="userUuid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="startReservation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="endReservation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReservationSoap", propOrder = {
    "uuid",
    "laneUuid",
    "userUuid",
    "startReservation",
    "endReservation"
})
public class ReservationSoap {

    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(required = true)
    protected String laneUuid;
    @XmlElement(required = true)
    protected String userUuid;
    @XmlElement(required = true)
    protected String startReservation;
    @XmlElement(required = true)
    protected String endReservation;

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the laneUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaneUuid() {
        return laneUuid;
    }

    /**
     * Sets the value of the laneUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaneUuid(String value) {
        this.laneUuid = value;
    }

    /**
     * Gets the value of the userUuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * Sets the value of the userUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserUuid(String value) {
        this.userUuid = value;
    }

    /**
     * Gets the value of the startReservation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartReservation() {
        return startReservation;
    }

    /**
     * Sets the value of the startReservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartReservation(String value) {
        this.startReservation = value;
    }

    /**
     * Gets the value of the endReservation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndReservation() {
        return endReservation;
    }

    /**
     * Sets the value of the endReservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndReservation(String value) {
        this.endReservation = value;
    }

}
